default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: cs_events_dev

test:
  <<: *default
  database: cs_events_test

production:
  <<: *default
  database: cs_events
